### PR TITLE
added description to get payments

### PR DESCRIPTION
**Pull request by nabeelamirch**
Added description to get payments.

resolves: GCI-962

### CODE REVIEW

**Comment by VaughanJackson123** [comment]
Do we need any API changes for this?

**Comment by nabeelamirch** [comment]
@VaughanJackson123 I have added this pr to update the specs https://github.com/companieshouse/api.ch.gov.uk-specifications/pull/158

**Comment by VaughanJackson123** [comment]
@nabeelamirch Good that you have updated the API spec! 
Sorry, I am a bit hazy about this, I was just wondering whether we needed to change the API SDK or whatever it's called? I guess not in this instance.

**Comment by nabeelamirch** [comment]
@VaughanJackson123, we don't have to update the sdk, because I just added an extra key value pair to a hash map. The sdk is already setup to handle it.

**Pull request merged**
